package t12p05;

import javax.swing.JOptionPane;
import modelo.ConexionBD;
import modelo.Referencia;
import modelo.Registro;

/**
 *
 * @author jesus
 */
public class PanelRegistroAlta extends javax.swing.JPanel {

    ConexionBD conn;
    Registro registro;
    boolean accion;
    
    public PanelRegistroAlta(ConexionBD conn) {
        initComponents();
        this.conn = conn;
    }

    void mostrar(Referencia referencia, boolean accion) {
        this.setVisible(true);
        this.registro = new Registro();
        this.accion = accion;
        txtIdProducto.setText(String.valueOf(referencia.getIdProducto()));
        txtIdProducto.setBackground(new java.awt.Color(200, 230, 250));
        txtNumReferencia.setText(referencia.getNumRef());
        txtNumReferencia.setBackground(new java.awt.Color(200, 230, 250));
        txtFechaAlta.setText(registro.getFecAlta());
        txtFechaAlta.setBackground(new java.awt.Color(200, 230, 250));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labCabecera = new javax.swing.JLabel();
        labIdProducto = new javax.swing.JLabel();
        labNumReferencia = new javax.swing.JLabel();
        labFechaAlta = new javax.swing.JLabel();
        labFechaBaja = new javax.swing.JLabel();
        labCausaBaja = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        txtNumReferencia = new javax.swing.JTextField();
        txtCausaBaja = new javax.swing.JTextField();
        txtFechaAlta = new javax.swing.JFormattedTextField();
        txtFechaBaja = new javax.swing.JFormattedTextField();
        botAceptar = new javax.swing.JButton();
        botCancelar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(620, 420));
        setMinimumSize(new java.awt.Dimension(620, 420));

        labCabecera.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        labCabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labCabecera.setText("ALTA REGISTRO");

        labIdProducto.setText("ID producto:");

        labNumReferencia.setText("Num. referencia:");

        labFechaAlta.setText("Fecha alta:");

        labFechaBaja.setText("Fecha baja:");

        labCausaBaja.setText("Causa baja:");

        txtIdProducto.setEditable(false);

        txtNumReferencia.setEditable(false);

        txtFechaAlta.setEditable(false);
        txtFechaAlta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        txtFechaBaja.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        botAceptar.setText("Aceptar");
        botAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAceptarActionPerformed(evt);
            }
        });

        botCancelar.setText("Cancelar");
        botCancelar.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labFechaAlta)
                            .addComponent(labFechaBaja)
                            .addComponent(labCausaBaja)
                            .addComponent(labIdProducto)
                            .addComponent(labNumReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdProducto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNumReferencia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFechaAlta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFechaBaja, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCausaBaja, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labCabecera)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labIdProducto)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNumReferencia)
                    .addComponent(txtNumReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labFechaAlta)
                    .addComponent(txtFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labFechaBaja)
                    .addComponent(txtFechaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCausaBaja)
                    .addComponent(txtCausaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botAceptar)
                    .addComponent(botCancelar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAceptarActionPerformed
        if (!txtFechaBaja.getText().equals("")) {
            registro.setIdProducto(Long.parseLong(txtIdProducto.getText()));
            registro.setNumRef(txtNumReferencia.getText());
            registro.setFecBaja(txtFechaBaja.getText());
            registro.setCausaBaja(txtCausaBaja.getText());
            if (accion) {
                registro.setAccion("BAJA");
            } else {
                registro.setAccion("ALTA");
            }
            
            try {
                registro.altaRegistro(conn);
            } catch (Exception e) {
                e.printStackTrace();
                ;
            }
        } else {
            JOptionPane.showConfirmDialog(this, 
                    "Debes de introducir fecha de baja", 
                    "ERROR", 
                    JOptionPane.OK_OPTION);
        }
        this.setVisible(false);
    }//GEN-LAST:event_botAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAceptar;
    private javax.swing.JButton botCancelar;
    private javax.swing.JLabel labCabecera;
    private javax.swing.JLabel labCausaBaja;
    private javax.swing.JLabel labFechaAlta;
    private javax.swing.JLabel labFechaBaja;
    private javax.swing.JLabel labIdProducto;
    private javax.swing.JLabel labNumReferencia;
    private javax.swing.JTextField txtCausaBaja;
    private javax.swing.JFormattedTextField txtFechaAlta;
    private javax.swing.JFormattedTextField txtFechaBaja;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNumReferencia;
    // End of variables declaration//GEN-END:variables

}
