package t12p05;

import javax.swing.JOptionPane;
import modelo.Aula;
import modelo.ConexionBD;

/**
 *
 * @author jesus
 */
public class PanelAulaAlta extends javax.swing.JPanel {

    ConexionBD conn;
    IBusCallBack ibc;
    boolean edicion;
    
    public PanelAulaAlta(ConexionBD conn) {
        initComponents();
        this.conn = conn;
    }

    void mostrar(IBusCallBack ibc) {
        this.setVisible(true);
        edicion = false;
        this.ibc = ibc;
        // Limpiar/inicializar campos
        txtNombre.setText("");
        txtDescripcion.setText("");
        try {
            txtId.setText(String.valueOf(Aula.generarId(conn)));
        } catch (Exception e) {
            //e.printStackTrace();
            ;
        }
    }
    
    void mostrarEdicion(IBusCallBack ibc, Aula aula) {
        this.setVisible(true);
        edicion = true;
        this.ibc = ibc;
        try {
            txtId.setText(String.valueOf(aula.getId()));
            txtNombre.setText(aula.getNombre());
            txtDescripcion.setText(aula.getDescripcion());
        } catch (Exception e) {
            //e.printStackTrace();
            ;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        labCabecera = new javax.swing.JLabel();
        labId = new javax.swing.JLabel();
        labNombre = new javax.swing.JLabel();
        labDescripcion = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        botAceptar = new javax.swing.JButton();
        botCancelar = new javax.swing.JButton();

        jTextField2.setText("jTextField1");

        setMaximumSize(new java.awt.Dimension(620, 420));
        setMinimumSize(new java.awt.Dimension(620, 420));

        labCabecera.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        labCabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labCabecera.setText("ALTA DE AULA");

        labId.setText("ID:");

        labNombre.setText("Nombre:");

        labDescripcion.setText("Descripcion:");

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(200, 230, 250));

        botAceptar.setText("Aceptar");
        botAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAceptarActionPerformed(evt);
            }
        });

        botCancelar.setText("Cancelar");
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labCabecera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botAceptar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labNombre)
                            .addComponent(labDescripcion)
                            .addComponent(labId))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtId))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labCabecera)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botAceptar)
                    .addComponent(botCancelar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botCancelarActionPerformed

    private void botAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAceptarActionPerformed
        Aula aula = new Aula();
        aula.setId(Integer.parseInt(txtId.getText()));
        aula.setNombre(txtNombre.getText());
        aula.setDescripcion(txtDescripcion.getText());
        if (!edicion) {
            try {
                aula.altaAula(conn);
                JOptionPane.showMessageDialog(this, 
                        "Alta correcta.",
                        "ALTA", 
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, 
                        "Error: " +e.getMessage(), 
                        "ERROR AL DAR DE ALTA", 
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            try {
                aula.updateAula(conn);
                JOptionPane.showMessageDialog(this, 
                        "Actualizacion correcta.",
                        "ACTUALIZAR", 
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                //e.printStackTrace();
                JOptionPane.showMessageDialog(this, 
                        "Error: " +e.getMessage(), 
                        "ERROR AL ACTUALIZAR", 
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        
        if (ibc != null) { ibc.callBack(); }
        this.setVisible(false);
    }//GEN-LAST:event_botAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAceptar;
    private javax.swing.JButton botCancelar;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labCabecera;
    private javax.swing.JLabel labDescripcion;
    private javax.swing.JLabel labId;
    private javax.swing.JLabel labNombre;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
