package t12p05;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ConexionBD;
import modelo.Registro;

/**
 *
 * @author jesus
 */
public class PanelRegistroBuscador extends javax.swing.JPanel {

    ConexionBD conn;
    DefaultTableModel modelo;
    
    public PanelRegistroBuscador(ConexionBD conn) {
        initComponents();
        this.conn = conn;
        modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[] {"NUM REFERENCIA", "ID PRODUCTO", "FECHA ALTA", "FECHA BAJA", "CAUSA BAJA", "ACCION" });
        tabRegistros.setModel(modelo);
    }

    void mostrar() {
        this.setVisible(true);
        modelo.setRowCount(0);
        txtFechaAlta1.setText("");
        txtFechaAlta2.setText("");
        txtFechaBaja1.setText("");
        txtFechaBaja2.setText("");
        txtIdProducto.setText("");
        txtNumReferencia.setText("");
    }
    
    /**
     * 
     * Por defecto busca en FechaAlta -> DESDE fecAlta con fecha mas antigua HASTA ahora.
     * Por defecto busca en FechaBaja -> DESDE ahora HASTA fecBaja con fecha mas lejana.
     * 
     * @return String[] con valores, en caso de escribir otra fecha, sustituye esa 
     * fecha por el campo por defecto.
     * @throws Exception 
     */
    private String[] fechaBuscador() throws Exception {
        try {
            String[] fechas = {"", "CURDATE()", "CURDATE()", ""};
        
            if (!txtFechaAlta1.getText().equals("")) {
                fechas[0] = "'" +Registro.TransformarFechaBBDD(txtFechaAlta1.getText()) +"'";
            } else {
                fechas[0] = "'" +Registro.obtenerFechaMenor(conn) +"'";
            }
            if (!txtFechaAlta2.getText().equals("")) {
                fechas[1] = "'" +Registro.TransformarFechaBBDD(txtFechaAlta2.getText()) +"'";
            }
            
            if (!txtFechaBaja1.getText().equals("")) {
                fechas[2] = "'" +Registro.TransformarFechaBBDD(txtFechaBaja1.getText()) +"'";
            }
            if (!txtFechaBaja2.getText().equals("")) {
                fechas[3] = "'" +Registro.TransformarFechaBBDD(txtFechaBaja2.getText()) +"'";
            } else {
                fechas[3] = "'" +Registro.obtenerFechaMayor(conn) +"'";
            }
        
            return fechas;
            
        } catch (Exception e) {
            throw new Exception("Error fechaBuscador()", e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labCabecera = new javax.swing.JLabel();
        labNumReferencia = new javax.swing.JLabel();
        labIdProducto = new javax.swing.JLabel();
        labFechaAlta = new javax.swing.JLabel();
        labFechaBaja = new javax.swing.JLabel();
        txtFechaAlta1 = new javax.swing.JFormattedTextField();
        txtFechaAlta2 = new javax.swing.JFormattedTextField();
        botBuscar = new javax.swing.JButton();
        botLimpiar = new javax.swing.JButton();
        txtNumReferencia = new javax.swing.JTextField();
        txtIdProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabRegistros = new javax.swing.JTable();
        botAceptar = new javax.swing.JButton();
        botCancelar = new javax.swing.JButton();
        botAlta = new javax.swing.JButton();
        botEditar = new javax.swing.JButton();
        botBaja = new javax.swing.JButton();
        labFechaAlta1 = new javax.swing.JLabel();
        labFechaBaja1 = new javax.swing.JLabel();
        txtFechaBaja1 = new javax.swing.JFormattedTextField();
        txtFechaBaja2 = new javax.swing.JFormattedTextField();

        setMaximumSize(new java.awt.Dimension(620, 420));
        setMinimumSize(new java.awt.Dimension(620, 420));

        labCabecera.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        labCabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labCabecera.setText("BUSCADOR REGISTRO");

        labNumReferencia.setText("Num. referencia:");

        labIdProducto.setText("ID producto:");

        labFechaAlta.setText("(fecha alta) DESDE:");

        labFechaBaja.setText("HASTA:");

        txtFechaAlta1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        txtFechaAlta2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        botBuscar.setText("Buscar");
        botBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBuscarActionPerformed(evt);
            }
        });

        botLimpiar.setText("Limpiar");
        botLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimpiarActionPerformed(evt);
            }
        });

        tabRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabRegistros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabRegistros.getTableHeader().setResizingAllowed(false);
        tabRegistros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabRegistros);

        botAceptar.setText("Aceptar");
        botAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAcepCancActionPerformed(evt);
            }
        });

        botCancelar.setText("Cancelar");
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAcepCancActionPerformed(evt);
            }
        });

        botAlta.setText("Alta");
        botAlta.setEnabled(false);

        botEditar.setText("Editar");
        botEditar.setEnabled(false);

        botBaja.setText("Baja");
        botBaja.setEnabled(false);

        labFechaAlta1.setText("(fecha baja) DESDE:");

        labFechaBaja1.setText("HASTA:");

        txtFechaBaja1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        txtFechaBaja2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(botAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botBaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botAceptar))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addComponent(labCabecera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labFechaAlta1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(labFechaAlta)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labIdProducto)
                            .addComponent(labNumReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumReferencia)
                            .addComponent(txtIdProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botLimpiar)
                            .addComponent(botBuscar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFechaBaja1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labFechaBaja1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFechaAlta1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labFechaBaja)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaAlta2)
                            .addComponent(txtFechaBaja2)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labCabecera)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botBuscar)
                    .addComponent(labIdProducto)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botLimpiar)
                    .addComponent(labNumReferencia)
                    .addComponent(txtNumReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labFechaAlta)
                    .addComponent(labFechaBaja)
                    .addComponent(txtFechaAlta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaAlta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labFechaAlta1)
                    .addComponent(labFechaBaja1)
                    .addComponent(txtFechaBaja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaBaja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botAceptar)
                    .addComponent(botCancelar)
                    .addComponent(botAlta)
                    .addComponent(botEditar)
                    .addComponent(botBaja))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBuscarActionPerformed
        // BUSCAR
        List<Registro> tRegistros = new ArrayList<>();
        try {
            String[] fechitas = fechaBuscador();
            Registro.buscarRegistro(conn, tRegistros, String.valueOf(txtIdProducto.getText()), 
                        txtNumReferencia.getText(), fechitas[0],fechitas[1],fechitas[2],fechitas[3]);
            
            modelo.setRowCount(0);
            Collections.sort(tRegistros);
            for (Registro t : tRegistros) {
                modelo.addRow(new String[] { 
                    t.getNumRef(),
                    String.valueOf(t.getIdProducto()),
                    t.getFecAlta(),
                    t.getFecBaja(),
                    t.getCausaBaja(),
                    t.getAccion()
                });
            }
        } catch (Exception e) {
            //e.printStackTrace();
            JOptionPane.showConfirmDialog(this, 
                    "Error cargar datos." +e.getMessage(), 
                    "ERROR", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botBuscarActionPerformed

    private void botLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimpiarActionPerformed
        mostrar();
    }//GEN-LAST:event_botLimpiarActionPerformed

    private void botAcepCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAcepCancActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botAcepCancActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAceptar;
    private javax.swing.JButton botAlta;
    private javax.swing.JButton botBaja;
    private javax.swing.JButton botBuscar;
    private javax.swing.JButton botCancelar;
    private javax.swing.JButton botEditar;
    private javax.swing.JButton botLimpiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labCabecera;
    private javax.swing.JLabel labFechaAlta;
    private javax.swing.JLabel labFechaAlta1;
    private javax.swing.JLabel labFechaBaja;
    private javax.swing.JLabel labFechaBaja1;
    private javax.swing.JLabel labIdProducto;
    private javax.swing.JLabel labNumReferencia;
    private javax.swing.JTable tabRegistros;
    private javax.swing.JFormattedTextField txtFechaAlta1;
    private javax.swing.JFormattedTextField txtFechaAlta2;
    private javax.swing.JFormattedTextField txtFechaBaja1;
    private javax.swing.JFormattedTextField txtFechaBaja2;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNumReferencia;
    // End of variables declaration//GEN-END:variables
}
