package t12p05;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ConexionBD;
import modelo.Referencia;

/**
 *
 * @author jesus
 */
public class PanelReferenciaBuscador extends javax.swing.JPanel implements IBusCallBack{

    ConexionBD conn;
    PanelReferenciaAlta pRefA;
    PanelRegistroAlta pRegA;
    DefaultTableModel modelo;
    
    public PanelReferenciaBuscador(ConexionBD conn, PanelReferenciaAlta pRefA, PanelRegistroAlta pRegA) {
        initComponents();
        this.conn = conn;
        this.pRefA = pRefA;
        this.pRegA = pRegA;
        modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[] { "ID PRODUCTO", "NUMERO REFERENCIA", "BAJA"});
        tabReferencias.setModel(modelo);
    }

    public void mostrar() {
        this.setVisible(true);
        modelo.setRowCount(0);
        txtIdProducto.setText("");
        txtNumReferencia.setText("");
        rboTodos.setSelected(true);
        rboSi.setSelected(false);
        rboNo.setSelected(false);
    }
    
    /**
     * Por defecto hay 3 opciones.
     *  1 - TODOS = ""
     *  2 - SI = "1"
     *  3 - NO = "0"
     * @return radioButton seleccionado.
     */
    private String baja() {
        String cat = "";
        
        if (rboSi.isSelected()) {
            cat = "1";
        }
        if (rboNo.isSelected()) {
            cat = "0";
        }
        
        return cat;
    }
    
    @Override
    public void callBack() {
        botBuscar.doClick();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGruBaja = new javax.swing.ButtonGroup();
        labCabecera = new javax.swing.JLabel();
        labIdProducto = new javax.swing.JLabel();
        labNumReferencia = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        txtNumReferencia = new javax.swing.JTextField();
        labBaja = new javax.swing.JLabel();
        rboTodos = new javax.swing.JRadioButton();
        rboSi = new javax.swing.JRadioButton();
        rboNo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabReferencias = new javax.swing.JTable();
        botAceptar = new javax.swing.JButton();
        botCancelar = new javax.swing.JButton();
        botEditar = new javax.swing.JButton();
        botBaja = new javax.swing.JButton();
        botBuscar = new javax.swing.JButton();
        botLimpiar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(620, 420));
        setMinimumSize(new java.awt.Dimension(620, 420));

        labCabecera.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        labCabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labCabecera.setText("BUSCADOR REFERENCIAS");

        labIdProducto.setText("ID Producto:");

        labNumReferencia.setText("Num. referencia:");

        labBaja.setText("Baja:");

        bGruBaja.add(rboTodos);
        rboTodos.setText("Todos");

        bGruBaja.add(rboSi);
        rboSi.setText("Si");

        bGruBaja.add(rboNo);
        rboNo.setText("No");

        tabReferencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabReferencias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabReferencias.getTableHeader().setResizingAllowed(false);
        tabReferencias.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabReferencias);

        botAceptar.setText("Aceptar");
        botAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAcepCancActionPerformed(evt);
            }
        });

        botCancelar.setText("Cancelar");
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAcepCancActionPerformed(evt);
            }
        });

        botEditar.setText("Editar");
        botEditar.setEnabled(false);

        botBaja.setText("Baja/Alta");
        botBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBajaActionPerformed(evt);
            }
        });

        botBuscar.setText("Buscar");
        botBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBuscarActionPerformed(evt);
            }
        });

        botLimpiar.setText("Limpiar");
        botLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labIdProducto)
                            .addComponent(labNumReferencia)
                            .addComponent(labBaja))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rboTodos)
                                .addGap(18, 18, 18)
                                .addComponent(rboSi)
                                .addGap(18, 18, 18)
                                .addComponent(rboNo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNumReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                    .addComponent(txtIdProducto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botLimpiar)
                                    .addComponent(botBuscar, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                            .addComponent(labCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botBaja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botAceptar)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labCabecera)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labIdProducto)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNumReferencia)
                    .addComponent(txtNumReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labBaja)
                    .addComponent(rboTodos)
                    .addComponent(rboSi)
                    .addComponent(rboNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botAceptar)
                    .addComponent(botEditar)
                    .addComponent(botBaja)
                    .addComponent(botCancelar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimpiarActionPerformed
        mostrar();
    }//GEN-LAST:event_botLimpiarActionPerformed

    private void botAcepCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAcepCancActionPerformed
        setVisible(false);
    }//GEN-LAST:event_botAcepCancActionPerformed

    private void botBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBuscarActionPerformed
        // BUSCAR
        List<Referencia> tReferencias = new ArrayList<>();
        try {
            Referencia.buscarReferencia(conn, tReferencias, txtIdProducto.getText(), txtNumReferencia.getText(), baja());
            modelo.setRowCount(0);
            
            Collections.sort(tReferencias);
            for (Referencia t : tReferencias) {
                modelo.addRow(new String[] {
                    String.valueOf(t.getIdProducto()),
                    t.getNumRef(),
                    (t.isBaja()?"SI":"NO")
                    });
            }
        } catch (Exception e) {
            //e.printStackTrace();
            JOptionPane.showConfirmDialog(this, 
                    "Error cargar datos.", 
                    "ERROR", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botBuscarActionPerformed

    private void botBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBajaActionPerformed
        if (tabReferencias.getSelectedRow() >= 0) {
            String idProducto = (String) modelo.getValueAt(tabReferencias.getSelectedRow(), 0);
            String numRef = (String) modelo.getValueAt(tabReferencias.getSelectedRow(), 1);
            String baja = (String) modelo.getValueAt(tabReferencias.getSelectedRow(), 2);
            // Referencia
            Referencia referencia = new Referencia(numRef, Long.parseLong(idProducto), !Boolean.parseBoolean(baja));
            
            try {
                pRegA.mostrar(referencia, !Boolean.parseBoolean(baja), this);
            } catch (Exception e) {
                ;
            }
        }
    }//GEN-LAST:event_botBajaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGruBaja;
    private javax.swing.JButton botAceptar;
    private javax.swing.JButton botBaja;
    private javax.swing.JButton botBuscar;
    private javax.swing.JButton botCancelar;
    private javax.swing.JButton botEditar;
    private javax.swing.JButton botLimpiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labBaja;
    private javax.swing.JLabel labCabecera;
    private javax.swing.JLabel labIdProducto;
    private javax.swing.JLabel labNumReferencia;
    private javax.swing.JRadioButton rboNo;
    private javax.swing.JRadioButton rboSi;
    private javax.swing.JRadioButton rboTodos;
    private javax.swing.JTable tabReferencias;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNumReferencia;
    // End of variables declaration//GEN-END:variables

}
